[package]
name = "parser"
version = "0.1.0"
authors = ["Jason Orendorff <jason.orendorff@gmail.com>"]
edition = "2018"

[dependencies]
generated_parser = { path = "../generated_parser" }
ast = { path = "../ast" }
elsa = "1.3"
