[package]
name = "driver"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]
edition = "2018"

[dependencies]
ast = { path = "../ast" }
emitter = { path = "../emitter" }
parser = { path = "../parser" }
jemallocator = "0.3.2"
